<?php

include_once CLASSES . 'AppSettingsDefinitions.class.php';
include_once CLASSES . 'Util.class.php';
include_once CLASSES . 'City.class.php';
include_once CLASSES . 'Database.class.php';

/**
 * This class is to handle the creation and loading of the applications
 * generated by the AGT
 */
class App {
    /*
     * Member variables are public in order 
     * to be serialized properly by json_encode
     */

    public $uid;
    public $name;
    public $description;
    public $userId;
    public $datasetIds;
    public $cityIds;
    public $color;
    public $darkColor;
    public $image;
    public $categoryNames;

    /**
     * Creates a new instance of the App object
     * @param string $uid the unique identifier of the app
     * @param string $name the name of the app
     * @param string $description the name of the app
     * @param string $userId the unique identifier of the user
     * @param string $datasetIds the array of dataset Ids for this application
     * @param string $cityIds  the array of city Ids for this application
     * @param string $color the main color of the app
     * @param string $darkColor the secondary color of the app
     * @param string $image the image of the app
     * @param string $categoryNames the array of category names for this application
     */
    public function __construct($uid, $name, $description, $userId, $datasetIds, $cityIds, $color, $darkColor, $image, $categoryNames) {
        $this->uid = $uid;
        $this->name = $name;
        $this->description = $description;
        $this->userId = $userId;
        $this->datasetIds = $datasetIds;
        $this->cityIds = $cityIds;
        $this->color = $color;
        $this->darkColor = $darkColor;
        $this->image = $image;
        $this->categoryNames = $categoryNames;
    }

    /**
     * Fetches an App instance from database based on the dataset id
     * @param array $assocArray an associative array representation of the object
     * @param int $userId the unique identifier of the user
     * @param string $image the image of the App
     * @return App|boolean an App instance or false on failure
     */
    public static function createFromDb($uid) {

        $sql = "SELECT * FROM apps where uid = :uid";
        $sqlParams[":uid"] = $uid;

        try {
            $sth = Database::$dbh->prepare($sql);
            $sth->execute($sqlParams);
            if ($result = $sth->fetch(PDO::FETCH_ASSOC)) {
                $uid = $result['uid'];
                $name = $result['name'];
                $description = $result['description'];
                $userId = $result['userId'];
                $image = $result['image'];
                $datasetIds = array();
                $cityIds = array();
                $categoryNames = array();

                // App found in database, now we load its settings
                $sql = "SELECT * FROM apps_settings WHERE app_uid = :uid";
                try {
                    $sth = Database::$dbh->prepare($sql);
                    $sth->execute($sqlParams);
                    while ($row = $sth->fetch(PDO::FETCH_ASSOC, PDO::FETCH_ORI_NEXT)) {
                        switch ($row["apps_settings_definition_id"]) {
                            case AppSettingsDefinitions::CITY: array_push($cityIds, $row['value']);
                                break;
                            case AppSettingsDefinitions::DATASET: array_push($datasetIds, $row['value']);
                                break;
                            case AppSettingsDefinitions::COLOR: $color = $row['value'];
                                break;
                            case AppSettingsDefinitions::DARKCOLOR: $darkColor = $row['value'];
                                break;
                            case AppSettingsDefinitions::CATEGORY: array_push($categoryNames, $row['value']);
                                break;
                            default:; //Do nothing
                        }
                    }
                    return new App($uid, $name, $description, $userId, $datasetIds, $cityIds, $color, $darkColor, $image, $categoryNames);
                } catch (Exception $e) {
                    if (DEBUG)
                        $sth->debugDumpParams();
                    Util::throwException(__FILE__, __LINE__, __METHOD__, "select app settings failed", $e->getMessage(), $e);
                    return false;
                }
            }
            else {
                return false;
            }
        } catch (Exception $e) {
            if (DEBUG)
                $sth->debugDumpParams();
            Util::throwException(__FILE__, __LINE__, __METHOD__, "select app uid failed", $e->getMessage(), $e);
        }
    }

    /**
     * Factory method that returns a new instance of an App
     * @param array $assocArray an associative array representation of the object
     * @param int $userId the unique identifier of the user
     * @param string $image the image of the App
     * @return App|boolean an App instance or false on failure
     */
    public static function createFromArray($assocArray, $userId, $image) {
        if (!empty($assocArray)) {
            $assocArray['datasetIds'] = explode(",", $assocArray['datasetIds']);
            // We will call a service that will give us a list of cities, based on the datasetIds
            // we provide it with
            
            $datasetIdsQueryString = "?format=json&datasetIds=";
            foreach ($assocArray['datasetIds'] as $datasetId) {
                $datasetIdsQueryString .= $datasetId . ",";
            }
            // Removing the trailing comma
            $datasetIdsQueryString = rtrim($datasetIdsQueryString, ",");

            $assocArray['categoryNames'] = explode(",", $assocArray['categoryNames']);
             $categoryNamesQueryString = "?format=json&categoryNames=";
            foreach ($assocArray['categoryNames'] as $categoryName) {
                $categoryNamesQueryString .= $categoryName . ",";
            }
            // Removing the trailing comma
            $categoryNamesQueryString = rtrim($categoryNamesQueryString, ",");

            // Clearing the cityIds array in case it has values, this can be removed when the appForm
            // stops providing cityIds
            $assocArray["cityIds"] = array();

            // Setting proxy settings
            if (PROXYUSE) {
                $aContext = array(
                    'http' => array(
                        'proxy' => 'tcp://' . PROXYNAME . ':' . PROXYPORT,
                        'request_fulluri' => true,
                    ),
                );
                $cxContext = stream_context_create($aContext);
            }
            else
                $cxContext = null;

            // Retrieving the cities from the index service
        //    $citiesInfoResponse = file_get_contents(CITIES_SERVICE . $datasetIdsQueryString, False, $cxContext);

            // Decoding the response
            $citiesInfoObj = json_decode($assocArray["cities"], true);

            // We need the id of each city. The ids come from the AGT database, and not
            // from the cities service
            foreach ($citiesInfoObj as $city) {
                
                $cityName = $city["name"];
                $cityLat = $city["lat"];
                $cityLon = $city["lon"];

                if (is_null($cityLat))
                    $cityLat = 0;

                if (is_null($cityLon))
                    $cityLon = 0;

                $cityId = City::getCityId($cityName, $cityLat, $cityLon);
                array_push($assocArray['cityIds'], $cityId);
            }
            
           

            return new App(null, $assocArray['name'], $assocArray['description'], $userId, $assocArray['datasetIds'], $assocArray['cityIds'], $assocArray['color'], $assocArray['darkColor'], $image, $assocArray['categoryNames']);
        }
        return false;
    }

    /**
     * Saves the App instance (AppId, AppName, AppDescription, DatasetIds[], CityIds[], ColorId)
     * to the database
     * @return true on success of false otherwise
     */
    public function save() {

        $this->uid = trim(Util::getGUID(), '{}');
        $sql = "INSERT INTO apps VALUES(:uid, :name, :userId, Now(), :description, :image, :isDeleted)";
        $sqlParams = array(':uid' => $this->uid, ':name' => $this->name, ':userId' => $this->userId, ':description' => $this->description, ':image' => $this->image, ':isDeleted' => 0);
        try {
            Database::connect();
            Database::begin();
            $sth = Database::$dbh->prepare($sql);
            $sth->execute($sqlParams);
        } catch (Exception $e) {
            if (DEBUG)
                $sth->debugDumpParams();
            Util::throwException(__FILE__, __LINE__, __METHOD__, "insert dataset failed", $e->getMessage(), $e);
            return false;
        }

        foreach ($this->datasetIds as &$datasetId) {
            $sql = "INSERT INTO apps_settings VALUES(null, :uid, :apps_settings_definition_id, :value)";
            $sqlParams = array(':uid' => $this->uid,
                ':apps_settings_definition_id' => AppSettingsDefinitions::DATASET,
                ':value' => $datasetId);
            try {
                $sth = Database::$dbh->prepare($sql);
                $sth->execute($sqlParams);
            } catch (Exception $e) {
                if (DEBUG)
                    $sth->debugDumpParams();
                Util::throwException(__FILE__, __LINE__, __METHOD__, "insert dataset failed", $e->getMessage(), $e);
                return false;
            }
        }
        foreach ($this->cityIds as &$cityId) {
            $sql = "INSERT INTO apps_settings VALUES(null, :uid, :apps_settings_definition_id, :value)";
            $sqlParams = array(':uid' => $this->uid,
                ':apps_settings_definition_id' => AppSettingsDefinitions::CITY,
                ':value' => $cityId);
            try {
                $sth = Database::$dbh->prepare($sql);
                $sth->execute($sqlParams);
            } catch (Exception $e) {
                if (DEBUG)
                    $sth->debugDumpParams();
                Util::throwException(__FILE__, __LINE__, __METHOD__, "insert city failed", $e->getMessage(), $e);
                return false;
            }
        }

        $sql = "INSERT INTO apps_settings VALUES(null, :uid, :apps_settings_definition_id, :value)";
        $sqlParams = array(':uid' => $this->uid,
            ':apps_settings_definition_id' => AppSettingsDefinitions::COLOR,
            ':value' => $this->color);
        try {
            $sth = Database::$dbh->prepare($sql);
            $sth->execute($sqlParams);
        } catch (Exception $e) {
            if (DEBUG)
                $sth->debugDumpParams();
            Util::throwException(__FILE__, __LINE__, __METHOD__, "insert color failed", $e->getMessage(), $e);
            return false;
        }

        $sql = "INSERT INTO apps_settings VALUES(null, :uid, :apps_settings_definition_id, :value)";
        $sqlParams = array(':uid' => $this->uid,
            ':apps_settings_definition_id' => AppSettingsDefinitions::DARKCOLOR,
            ':value' => $this->darkColor);
        try {
            $sth = Database::$dbh->prepare($sql);
            $sth->execute($sqlParams);
        } catch (Exception $e) {
            if (DEBUG)
                $sth->debugDumpParams();
            Util::throwException(__FILE__, __LINE__, __METHOD__, "insert dark color  failed", $e->getMessage(), $e);
            return false;
        }

        foreach ($this->categoryNames as &$categoryName) {
            $sql = "INSERT INTO apps_settings VALUES(null, :uid, :apps_settings_definition_id, :value)";
            $sqlParams = array(':uid' => $this->uid,
                ':apps_settings_definition_id' => AppSettingsDefinitions::CATEGORY,
                ':value' => $categoryName);
            try {
                $sth = Database::$dbh->prepare($sql);
                $sth->execute($sqlParams);
            } catch (Exception $e) {
                if (DEBUG)
                    $sth->debugDumpParams();
                Util::throwException(__FILE__, __LINE__, __METHOD__, "insert category failed", $e->getMessage(), $e);
                return false;
            }
        }

        return true;
    }

}

?>